// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAhrvI2S2rKhp-hiBfPTmR1y7nhETFTaA',
    appId: '1:948735354770:web:667cb78481b19bf955434b',
    messagingSenderId: '948735354770',
    projectId: 'to-yudi',
    authDomain: 'to-yudi.firebaseapp.com',
    storageBucket: 'to-yudi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDidOKQoSNguUvZGIZGLj3BIKMMHBLoS6A',
    appId: '1:948735354770:android:e78a8229b5eda78a55434b',
    messagingSenderId: '948735354770',
    projectId: 'to-yudi',
    storageBucket: 'to-yudi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUfDpIflvBsqh4SZAGOB70NLxqXdVlazA',
    appId: '1:948735354770:ios:aee73d7f07d052bf55434b',
    messagingSenderId: '948735354770',
    projectId: 'to-yudi',
    storageBucket: 'to-yudi.firebasestorage.app',
    iosBundleId: 'com.example.toYudi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAhrvI2S2rKhp-hiBfPTmR1y7nhETFTaA',
    appId: '1:948735354770:web:ff70e92573d8eab055434b',
    messagingSenderId: '948735354770',
    projectId: 'to-yudi',
    authDomain: 'to-yudi.firebaseapp.com',
    storageBucket: 'to-yudi.firebasestorage.app',
  );
}
